[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[doc]
# Ignore specific patterns using glob patterns
ignore = [
    "./src/math/*",
    "./src/mocks/*",
]
# Remove src prefix from paths
strip_prefix = "src/"