name: Test and Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-coverage:
    name: Run Tests and Generate Coverage
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Install Dependencies
        run: |
          forge install OpenZeppelin/openzeppelin-contracts
          forge install foundry-rs/forge-std
          forge build

      - name: Run Tests with Coverage
        run: |
          forge coverage --report lcov
          genhtml lcov.info -o docs/coverage

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Coverage Report
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 